CREATE DATABASE BIBLIOTECA;

USE ACADEMIADOTNET;
DROP DATABASE BIBLIOTECA;


USE BIBLIOTECA;

CREATE TABLE categoria
(
	ID INTEGER PRIMARY KEY IDENTITY,
	nome VARCHAR(50) NOT NULL,
	descricao TEXT NOT NULL
);

CREATE TABLE autor
(
	ID INTEGER PRIMARY KEY IDENTITY,
	nome VARCHAR(100) NOT NULL,
	nacionalidade VARCHAR (20) NOT NULL
);

CREATE TABLE editora
(
	ID INTEGER PRIMARY KEY IDENTITY,
	nome VARCHAR(20) NOT NULL
);

CREATE TABLE livro
(
	isbn VARCHAR(22) PRIMARY KEY NOT NULL,
	titulo VARCHAR(50) NOT NULL,
	fk_categoria INTEGER,
	fk_editora INTEGER,
	FOREIGN KEY (fk_categoria) REFERENCES categoria(ID),
	FOREIGN KEY (fk_editora) REFERENCES editora(ID)
);

CREATE TABLE livro_autor
(
	id INTEGER PRIMARY KEY IDENTITY,
	fk_autor INTEGER NOT NULL,
	fk_livro VARCHAR(22) NOT NULL,
	FOREIGN KEY (fk_livro) REFERENCES livro(isbn),
	FOREIGN KEY (fk_autor) REFERENCES autor(ID)
);